plugins:
  - jest

env:
  node: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  import/extensions: 0
    - error
    - ignorePackages
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  indent:
    - error
    - tab
  quotes:
    - error
    - single
